### ISSUE TITLE
git user.email and user.name should be set on Debian/Ubuntu

### ISSUE THREAD

**Issue by monotek** [bodgit/puppet-etckeeper#3]
If git is used the git configuration should be done for etckeeper.
After installing a new package onCentOS 7 i got:

```
etckeeper: post transaction commit

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@centos.(none)')
warning: etckeeper failed to commit changes in /etc using git

```

**Comment by monotek** [comment]
Hmm... maybe this is superfluous.
Even there is an error message there is a commit in the git log anyway.

I tried to set user.email & user.name via GIT_COMMIT_OPTIONS but run into another errore because it seems only on of the git options "-c/-C/-F/--fixup" can be used.

**Comment by monotek** [comment]
The problem only occurs on centos if you login via root directly. 
Login as non root user and becoming root via su solves teh problem.
I guess problem hast to be fixed in etckeeper.

**Comment by monotek** [comment]
Reopening because there still some problems on Debian 7, Ubuntu 12.04 - Ubuntu 16.04.
Problem occurs when unattended.upgrades are installed. Cronjob sends mails like:

```
Unattended upgrade returned: True

Warning: A reboot is required to complete this upgrade.

Packages that were upgraded:
 libfreetype6 

Package installation log:
Log started: 2017-03-21  00:08:00
[master 447e7d8] saving uncommitted changes in /etc prior to apt run
 Committer: root <root@your.server>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 2 insertions(+), 2 deletions(-)
```
I'll reopen the old pull request with some changes.

**Comment by bodgit** [comment]
So this is actually just an annoying noisy warning, it's not stopping the commits. Git does support `GIT_AUTHOR_NAME` and `GIT_AUTHOR_EMAIL` which is what etckeeper sets if it thinks someone has used `su` or `sudo` to become root.
