### ISSUE TITLE
Add config switch if vcs package should be installed

### ISSUE THREAD

**Issue by monotek** [bodgit/puppet-etckeeper#5]
We have git package already defined in another puppet module.

Would be nice vcs package install is configurable

**Comment by bodgit** [comment]
It's using the `ensure_packages()` function so it shouldn't be causing a resource conflict, unless you're installing git from a different package to the one provided by the OS?

**Comment by monotek** [comment]
Yes, git already comes from another puppet module.

**Comment by bodgit** [comment]
One temporary workaround is to make my etckeeper module depend on your git module if they're both trying to manage the same package.

**Comment by monotek** [comment]
At the moment i just removed the git package from the other module.
I'll create pull request later this week to have it optional in etckeeper.

**Comment by monotek** [comment]
Added pull request: https://github.com/bodgit/puppet-etckeeper/pull/6

**Comment by bodgit** [comment]
I just pushed a similar fix and it's up on the forge as version 1.1.0.

Thanks for the bug report!

**Comment by bodgit** [comment]
I just pushed a similar fix and it's up on the forge as version 1.1.0.

Thanks for the bug report!
