### ISSUE TITLE
Is there any way to exclude files via the module?

### ISSUE THREAD

**Issue by monotek** [bodgit/puppet-etckeeper#7]
We have a proxmox host which uses /etc/pve/.rrd to write rrd data :-/
Etckeeper constantly complains when installing new packages about uncommitted changes.

```
Preconfiguring packages ...
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   pve/local
#       modified:   pve/openvz
#       modified:   pve/qemu-server
#
no changes added to commit (use "git add" and/or "git commit -a")
E: Problem executing scripts DPkg::Post-Invoke 'if [ -x /usr/bin/etckeeper ]; then etckeeper post-install; fi'
E: Sub-process returned an error code
E: Sub-process /usr/bin/dpkg returned an error code (2)
```
Manual run via:

```
$ git add --all .;git commit -m "manual entry"
[master ae42962] manual entry
 1 file changed, 29 insertions(+), 29 deletions(-)
 rewrite pve/.rrd (81%)
```
Fixes it only until next run.

**Comment by monotek** [comment]
Temporary solution:

git rm --cached -r pve
echo 'pve/*' >> /etc/.gitignore
etckeeper commit -m "remove pve folder"

**Comment by bodgit** [comment]
In theory this requires just managing the `.gitignore` file somehow however I don't want to end up fighting with etckeeper if it wants to manage its own block of ignores. Ideally I would want something that works for each of the supported VCS if they also have a way of ignoring files.

**Comment by bodgit** [comment]
So etckeeper runs `etckeeper update-ignore` to generate the list of ignores in whatever form each VCS wants. Any patterns added before or after the magic `managed by etckeeper` comments are retained but if they're within those comments then a subsequent run of `etckeeper update-ignore` will trash them. So ideally I need a way of managing just that bit of the file.

**Comment by bodgit** [comment]
I've added a defined type for adding entries to the bottom of `.gitignore`, etc. You'd do something like:
```puppet
::etckeeper::ignore { 'pve/*':
  ensure => present,
}
```

**Comment by monotek** [comment]
Thanks a lot. Works :-)

**Comment by monotek** [comment]
Ah... One last thing.
The already existing entries in git also needs to be removed. Adding the following command should do the trick for git:
* git rm --cached -r pve
